VentaPasajes/PresentacionWeb/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentacionWeb.Controllers
{
    public class ErrorController : Controller
    {
        //
        // GET: /Error/
        public ActionResult Index(String mensaje)
        {
            ViewBag.mensaje = mensaje;
            return View();
        }
	}
}

VentaPasajes/PresentacionWeb/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentacionWeb.Controllers
{
    public class InicioController : Controller
    {
        [HttpGet]
        public ActionResult Index(short? i, String Mensaje)
        {
            ViewBag.i = i;
            ViewBag.m = Mensaje;
            return View();
        }
        [HttpPost]
        public ActionResult Index(FormCollection frm) {
            try
            {
                String nombre = frm["nombre"].ToString();
                return RedirectToAction("Index", new {i = 1, mensaje="Hola "+nombre});
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", new { i = 2, mensaje = ex.Message });
            }
        }
	}
}

VentaPasajes/PresentacionWeb/Controllers/IntranetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaAplicacion;
using CapaDominio;

namespace PresentacionWeb.Controllers
{
    public class IntranetController : Controller
    {
        //
        // GET: /Intranet/
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(FormCollection frm)
        {

            try
            {
                String user = frm["txtUser"].ToString();
                String pass = frm["txtPassword"].ToString();

                if (appUsuario.Instancia.VerificarAcceso(user, pass))
                {
                    return RedirectToAction("Bienvenido");
                }
                else
                {
                    //ViewBag.mensaje = "User o Pass No Valido..!!!!";
                    //return View();
                    return RedirectToAction("Index", "Error", new { mensaje = "User o Pass No Valido..!!!!" });
                    
                }
            }
            catch (Exception e)
            {

                return RedirectToAction("Index", "Error", new {mensaje=e.Message });
            }

        }

        public ActionResult Bienvenido()
        {

            return View();
        }
    }
}

VentaPasajes/PresentacionWeb/Views/Inicio/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head lang="es">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="~/Desing/css/bootstrap.min.css" rel="stylesheet" />
    
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->

    <title>Ingreso</title>
</head>
<body class="container">
    <div class="row">
        @Html.ActionLink("IR INTRANET","Login","Intranet");
        <h3>
            <i class="glyphicon glyphicon-eye-open"></i>
            Hello world
        </h3>
        <form method="post" class="col-lg-12">
            <div class="form-group">
                <input name="Nombre" class="form-control" placeholder="Nombre" />
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> Agregar</button>
            </div>

</form>
        <div class="col-lg-12">
            @{
                if (ViewBag.m != null)
                {
                    if (ViewBag.i == 1)
                    {
                        <div class="alert alert-info" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>@ViewBag.m</div>
                    }
                    else if (ViewBag.i == 2)
                    {
                        <div class="alert alert-danger" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>@ViewBag.m</div>
                    }
                }
            }
        </div>
    </div>

    <!--
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    -->
    <script src="~/Desing/js/bootstrap.min.js"></script>
</body>
</html>

VentaPasajes/PresentacionWeb/Views/Intranet/Bienvenido.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Bienvenido</title>
</head>
<body>
    <div> 
        <h2>Bienvenido</h2>
    </div>
</body>
</html>

VentaPasajes/PresentacionWeb/Views/Intranet/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Desing/css/bootstrap.min.css" rel="stylesheet" />
    <title>Login</title>
</head>
<body>
    <div>
        <center>
            Acceso a INTRANET
        </center>
        <br />
        <form method="post" action="Login">

            <center>
                <table>
                    <tr>
                        <td>Usuario</td>
                        <td> <input type="text" name="txtUser" /> </td>
                    </tr>
                    <tr>
                        <td>Password</td>
                        <td><input type="password" name="txtPassword" /></td>
                    </tr>
                    <tr>
                        <td colspan="2" align="center">

                            <input type="submit" class="btn btn-success" value="INGRESAR" />
                            <input type="submit" class="btn btn-danger" value="CANCEL" />

                        </td>
                    </tr>
                </table>
                @ViewBag.mensaje
            </center>

        </form>
       

    </div>
</body>
</html>